### DISCUSSION TITLE
A more generic framework

### DISCUSSION THREAD

**Discussion by BioBoost** [vives-dust/framework#20] [Ideas]
Idea is to build a generic sensor platform for all sorts of devices. Some may even be non-physical sensors such as another API (take for example open weather map).

These devices are defined in yaml files and should be automatically loaded into our platform.

Basically we can define specs for devices. Take a look at the example below which is a spec for a `dust-device`:

```yaml
name: dust-device
props:
  - geolocatable
sensors:
  - temperature:
    - source: influxdb
  - moisture:
    - source: influxdb
    - amount: 4
    - converters:
      - model
  - battery:
    - source: influxdb
```

This basically defines that our device has a location and 5 sensors. 4 moisture sensors and 1 temperature sensor. This defines what information will be required when a device is created via API, what data will be returned, what post-processing steps are required for each sensor (converters).

Now when we create a new device via API, we can define what type of device we are creating (while all the actual details that can be provided are defined in the device spec):

```json
{
  "device": "dust-device",
  "devId": "eui-70b3d57ed004a669",
  "location": {
    "longitude": 51.3,
    "latitude": 33.2
  },
  "sensors": [
    {
      "type": "temperature",
      "influxdb": {
        "field": "internalTemperature",
      }
    },
    {
      "type": "moisture",
      "influxdb": {
        "field": "moistureLevel_1", 
      },
      "model": "leemzand_v23",
      "depth": -3
    },
    {
      "type": "moisture",
      "influxdb": {
        "field": "moistureLevel_2", 
      },
      "model": "leemzand_v23",
      "depth": -9
    },
    {
      "type": "moisture",
      "influxdb": {
        "field": "moistureLevel_3", 
      },
      "model": "leemzand_v23",
      "depth": -16
    },
    {
      "type": "moisture",
      "influxdb": {
        "field": "moistureLevel_4", 
      },
      "model": "leemzand_v23",
      "depth": -22
    },
    {
      "type": "battery",
      "influxdb": {
        "field": "battery", 
      }
    },
  ]
}
```
