### ISSUE TITLE
Docker-compose production influxdb2 labels

### ISSUE THREAD

**Issue by BioBoost** [vives-dust/framework#5]
Seems like there is a copy paste error in the docker-compose file where influxdb is also exposed to the outside:

```yml
    labels:
      traefik.enable: true
      traefik.http.routers.dust_grafana.rule: Host(`${APPLICATION_DOMAIN_NAME}`)
      traefik.http.services.dust_grafana.loadbalancer.server.port: 8086
      traefik.docker.network: reverse_proxy
```

I think this can be deleted.
